<?php

namespace App\Http\Controllers;

use App\Blocks;
use Validator, Input, Redirect, View, Auth;
use App\Mnl;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\elasticSearch;

class ActiveList extends Controller
{
	public function coinList()
	{
		$i                         = 0;
		$coin                      = [];
		$coin['name']              = 'ION';
		$coin['coin']              = 'ion';
		$coin['listed']            = '05/01/2016';
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'iond';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['logo']              = '//ion.masternodes.pro/img/logo.png';
		$coins[$i]                 = $coin;
		$i++;


		$coin                      = [];
		$coin['name']              = 'Braincoin';
		$coin['coin']              = 'BRAIN';
		$coin['listed']            = '08/15/2017';
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'brain-cli';
		$coin['url']               = 'https://cryptocointalk.com/topic/46137-braincoin-info-powpossoon';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/braincoin.png';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Cream';
		$coin['coin']              = 'crm';
		$coin['url']               = 'https://creamcoin.com/';
		$coin['listed']            = '08/14/2017';
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'creamd';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/cream.png';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'DAS';
		$coin['coin']              = 'das';
		$coin['listed']            = '08/08/2017';
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'das-cli';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/das.png';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coins[$i]                 = $coin;
		$i++;

		$coin                      = [];
		$coin['name']              = 'SIBCoin';
		$coin['coin']              = 'SIB';
		$coin['url']               = 'http://sibcoin.org/';
		$coin['listed']            = '08/01/2017';
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'sibcoin-cli';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/sibcoin.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Linda';
		$coin['coin']              = 'linda';
		$coin['url']               = 'http://lindacoin.com/';
		$coin['listed']            = '08/01/2017';
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'Linda';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/linda.png';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Crown';
		$coin['coin']              = 'CRW';
		$coin['listed']            = '07/31/2017';
		$coin['url']               = 'http://crown.tech/';
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'crown-cli';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/crown.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Renos';
		$coin['coin']              = 'RNS';
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'renosd';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['listed']            = '07/27/2017';
		$ads['start']              = '07/27/2017';
		$ads['end']                = '08/28/2017';
		$ads['cost']               = '5000RNS';
		$ads['location']           = 'top';
		$ads['type']               = 'list';
		$coin['ads']               = $ads;
		$coin['url']               = 'https://renoscoin.com/?track=MNP';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/renos.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'ChainCoin';
		$coin['coin']              = 'chc';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'chaincoin-cli';
		$coin['badroi']            = true;
		$coin['logo']              = '//chc.masternodes.pro/img/logo.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'PIVX';
		$coin['coin']              = 'pivx';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'pivx-cli';
		$coin['badroi']            = true;
		$coin['logo']              = 'https://raw.githubusercontent.com/PIVX-Project/Official-PIVX-Graphics/master/digital/bottom%20tag/portrait/White/White_Port.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Neutron';
		$coin['coin']              = 'ntrn';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'Neutrond';
		$coin['logo']              = 'https://static.wixstatic.com/media/f2591a_f17f4b3fcbb74848b2bccf59bbeae490~mv2.png/v1/fill/w_708,h_520,al_c,lg_1/f2591a_f17f4b3fcbb74848b2bccf59bbeae490~mv2.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'ArcticCoin';
		$coin['coin']              = 'arc';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'arcticcoin-cli';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/arcticcoin.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'CRAVE';
		$coin['coin']              = 'crave';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = true;
		$coin['tagable']['daemon'] = 'craved';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/crave.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'MonetaryUnit';
		$coin['coin']              = 'MUE';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'mue-cli';
		$coin['url']               = 'http://www.monetaryunit.org/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/monetaryunit.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'ExclusiveCoin';
		$coin['coin']              = 'EXCL';
		$coin['listed']            = '07/27/2017';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'exclusivecoind';
		$coin['url']               = 'http://exclusivecoin.pw/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/exclusivecoin.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'DASH';
		$coin['coin']              = 'DASH';
		$coin['listed']            = '07/27/2017';
		$coin['tagable']['active'] = false;
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['daemon'] = 'dash-cli';
		$coin['url']               = 'https://www.dash.org/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/dash.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Syndicate';
		$coin['coin']              = 'SYNX';
		$coin['listed']            = '07/27/2017';
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'Syndicated';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['url']               = 'http://syndicatelabs.io/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/syndicate.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Eternity';
		$coin['coin']              = 'ent';
		$coin['listed']            = '07/27/2017';
		$coin['tagable']['active'] = false;
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['tagable']['daemon'] = 'eternity-cli';
		$coin['url']               = 'http://ent.eternity-group.org/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/eternity.png';
		$coins[$i]                 = $coin;
		$i++;
		$coin                      = [];
		$coin['name']              = 'Bitsend';
		$coin['coin']              = 'bsd';
		$coin['tagable']['active'] = false;
		$coin['tagable']['daemon'] = 'bitsend-cli';
		$coin['notes']             = "New Wallet, Moving DB to ElasticSearch, New Stats Site!";
		$coin['url']               = 'http://www.bitsend.info/';
		$coin['logo']              = 'https://files.coinmarketcap.com/static/img/coins/128x128/bitsend.png';
		$coins[$i]                 = $coin;
		$i++;
		return $coins;
	}
}